# Generated by Django 5.1.7 on 2025-05-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genre', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_year', models.IntegerField()),
                ('synopsis', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movie_posters/')),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('genres', models.ManyToManyField(related_name='movies', to='genre.genre')),
                ('people', models.ManyToManyField(related_name='movies', to='person.person')),
            ],
        ),
    ]
